# Generated by Django 5.0.3 on 2024-06-18 21:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations
from django.db import models

import core.models.order


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_fulfilled", models.BooleanField(default=False)),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_phone", models.CharField(max_length=15, null=True)),
                (
                    "customer_mobile",
                    models.CharField(max_length=15, null=True),
                ),
                (
                    "customer_company_name",
                    models.CharField(max_length=200, null=True),
                ),
                (
                    "customer_company_ref",
                    models.CharField(max_length=200, null=True),
                ),
                (
                    "customer_address_street_line_1",
                    models.CharField(max_length=200, null=True),
                ),
                (
                    "customer_address_street_line_2",
                    models.CharField(max_length=200, null=True),
                ),
                (
                    "customer_address_suburb",
                    models.CharField(max_length=50, null=True),
                ),
                (
                    "customer_address_state",
                    models.CharField(max_length=3, null=True),
                ),
                (
                    "customer_address_post_code",
                    models.CharField(max_length=4, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assessment", models.CharField(max_length=50)),
                ("lot", models.CharField(max_length=50)),
                ("section", models.CharField(max_length=50)),
                ("deposited_plan", models.CharField(max_length=50)),
                ("address_street", models.CharField(max_length=50, null=True)),
                ("address_suburb", models.CharField(max_length=50, null=True)),
                ("address_state", models.CharField(max_length=50, null=True)),
                (
                    "address_post_code",
                    models.CharField(max_length=50, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "properties",
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "fees",
                    models.ManyToManyField(related_name="fees", to="core.fee"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_fulfilled", models.BooleanField(default=False)),
                (
                    "certificate_file",
                    models.FileField(
                        null=True,
                        upload_to=core.models.order.certificate_file_directory_path,
                    ),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.certificate",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.order",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="certificate",
            field=models.ManyToManyField(
                through="core.OrderLine", to="core.certificate"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.property"
            ),
        ),
    ]
