# Generated by Django 5.0.3 on 2024-06-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.EmailField(
                default="customer@example.com", max_length=254
            ),
            preserve_default=False,
        ),
    ]
