# Generated by Django 5.0.3 on 2024-06-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fee",
            name="name",
            field=models.CharField(max_length=254),
        ),
    ]
