# Generated by Django 5.0.3 on 2024-06-16 04:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_certificate_created_at_certificate_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assessment", models.CharField(verbose_name=50)),
                ("lot", models.CharField(verbose_name=50)),
                ("section", models.CharField(verbose_name=50)),
                ("deposited_plan", models.CharField(verbose_name=50)),
                (
                    "address_street",
                    models.CharField(null=True, verbose_name=50),
                ),
                (
                    "address_suburb",
                    models.CharField(null=True, verbose_name=50),
                ),
                (
                    "address_state",
                    models.CharField(null=True, verbose_name=50),
                ),
                (
                    "address_post_code",
                    models.CharField(null=True, verbose_name=50),
                ),
            ],
        ),
    ]
