# Generated by Django 5.0.3 on 2024-06-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0003_certificate_price_certificate_stripe_price_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="fees",
            field=models.ManyToManyField(
                blank=True, related_name="fees", to="core.fee"
            ),
        ),
    ]
