# Generated by Django 5.0.3 on 2024-06-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_property"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="address_post_code",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="address_state",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="address_street",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="address_suburb",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="assessment",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="property",
            name="deposited_plan",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="property",
            name="lot",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="property",
            name="section",
            field=models.CharField(max_length=50),
        ),
    ]
