# Generated by Django 5.0.3 on 2024-06-16 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_property_address_post_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={"verbose_name_plural": "properties"},
        ),
    ]
