# Generated by Django 5.0.3 on 2024-07-08 21:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_fee_created_at_fee_price_fee_stripe_price_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="certificate",
            new_name="lines",
        ),
        migrations.RemoveField(
            model_name="order",
            name="customer_mobile",
        ),
        migrations.AddField(
            model_name="order",
            name="customer_address_country",
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="orderline",
            name="fee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.fee",
            ),
        ),
        migrations.CreateModel(
            name="OrderSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stripe_checkout_id", models.CharField(max_length=255)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.property",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="order_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.ordersession",
            ),
        ),
        migrations.CreateModel(
            name="OrderSessionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.certificate",
                    ),
                ),
                (
                    "fee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.fee",
                    ),
                ),
                (
                    "order_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.ordersession",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ordersession",
            name="lines",
            field=models.ManyToManyField(
                through="core.OrderSessionLine", to="core.certificate"
            ),
        ),
    ]
