# Generated by Django 5.0.3 on 2024-07-04 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_order_customer_mobile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="fee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.fee",
            ),
        ),
    ]
