# Generated by Django 5.0.3 on 2024-06-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_order_certificate_orderline_order_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="certificate_file",
            field=models.FileField(
                null=True, upload_to="certificate_file_directory_path"
            ),
        ),
    ]
