# Generated by Django 5.0.3 on 2024-07-07 20:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_orderline_fee"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderSessionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.certificate",
                    ),
                ),
                (
                    "fee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.fee",
                    ),
                ),
                (
                    "order_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.ordersession",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ordersession",
            name="certificate",
            field=models.ManyToManyField(
                through="core.OrderSessionLine", to="core.certificate"
            ),
        ),
    ]
