# Generated by Django 5.0.3 on 2024-06-16 06:20

import core.models.order
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_orderline_certificate_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderline",
            name="certificate_file",
            field=models.FileField(
                null=True,
                upload_to=core.models.order.certificate_file_directory_path,
            ),
        ),
    ]
