# Generated by Django 5.0.3 on 2024-07-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_orderline_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordersession",
            name="stripe_session_id",
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
