# Generated by Django 5.0.3 on 2024-06-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_order_is_fulfilled"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_fulfilled",
            field=models.BooleanField(default=False),
        ),
    ]
