# Generated by Django 5.0.3 on 2024-07-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_order_order_session"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordersession",
            old_name="certificate",
            new_name="lines",
        ),
    ]
