# Generated by Django 5.0.3 on 2024-07-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_rename_certificate_ordersession_lines"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="certificate",
            new_name="lines",
        ),
    ]
