# Generated by Django 5.0.3 on 2024-07-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_rename_certificate_order_lines"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordersession",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Pending"), (2, "Completed"), (3, "Error")],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="ordersession",
            name="status_error",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
