# Generated by Django 5.0.3 on 2024-07-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_ordersession_status_ordersession_status_error"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordersession",
            name="status_error",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
