# Generated by Django 5.0.3 on 2024-07-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_order_customer_address_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="account_code",
            field=models.CharField(default="CERT-100", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="certificate",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
