# Generated by Django 5.0.3 on 2024-07-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_certificate_account_code_certificate_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="fulfilled_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
