# Generated by Django 5.0.3 on 2024-07-23 21:29

import core.models.order
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_certificate_account_code_certificate_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_name",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="fulfilled_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="orderline",
            name="cost_certificate",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderline",
            name="cost_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="orderline",
            name="fulfilled_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="ordersessionline",
            name="cost_certificate",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ordersessionline",
            name="cost_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="certificate_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=core.models.order.certificate_file_directory_path,
            ),
        ),
    ]
