# Generated by Django 5.0.3 on 2024-07-24 20:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_order_customer_name_order_fulfilled_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_hash",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
