# Generated by Django 5.0.3 on 2024-07-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_order_fulfilled_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="fulfilled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
