# Generated by Django 5.0.3 on 2024-07-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_order_fulfilled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="fulfilled_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
