# Generated by Django 5.0.3 on 2024-07-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_orderline_fulfilled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_name",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
