# Generated by Django 5.0.3 on 2024-07-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_order_customer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer_name",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
