# Generated by Django 5.0.3 on 2024-08-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_settings_council_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stripe_checkout_id",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ordersession",
            name="customer_company_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="ordersession",
            name="customer_name",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
