# Generated by Django 5.0.3 on 2024-07-23 20:45

import core.models.order
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_order_customer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderline",
            name="certificate_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=core.models.order.certificate_file_directory_path,
            ),
        ),
    ]
