# Generated by Django 5.0.3 on 2024-08-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_order_stripe_checkout_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordersession",
            name="customer_address_country",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="ordersession",
            name="customer_address_post_code",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="ordersession",
            name="customer_address_state",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="ordersession",
            name="customer_address_street_line_1",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="ordersession",
            name="customer_address_street_line_2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="ordersession",
            name="customer_address_suburb",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ordersession",
            name="customer_company_ref",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="ordersession",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
