# Generated by Django 5.0.3 on 2024-08-09 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_taxrate_orderline_tax_amount_certificate_and_more"),
        ("core", "0029_remove_order_stripe_checkout_id"),
    ]

    operations = []
