# Generated by Django 5.0.3 on 2024-08-10 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_remove_order_stripe_checkout_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "child_certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_bundles",
                        to="core.certificate",
                    ),
                ),
                (
                    "parent_certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_bundles",
                        to="core.certificate",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("parent_certificate", "child_certificate")
                },
            },
        ),
    ]
