# Generated by Django 5.0.3 on 2024-08-21 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_ordersessionline_tax_amount_certificate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="child_certificates",
            field=models.ManyToManyField(
                blank=True,
                related_name="parent_certificates",
                to="core.certificate",
            ),
        ),
        migrations.AlterField(
            model_name="taxrate",
            name="percentage",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
