# Generated by Django 5.0.3 on 2024-08-21 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_ordersessionline_tax_amount_certificate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="child_certificates",
            field=models.ManyToManyField(
                blank=True,
                related_name="parent_certificates",
                to="core.certificate",
            ),
        ),
    ]
