# Generated by Django 5.0.3 on 2024-08-25 03:50

from django.db import migrations, models




class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_certificate_child_certificates_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='certificate',
                    name='is_active',
                    field=models.BooleanField(default=True),
                ),
            ],
        ),
    ]
