# Generated by Django 5.0.3 on 2024-08-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_certificate_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="is_active",
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
