# Generated by Django 5.0.3 on 2024-08-25 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_alter_certificate_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxrate",
            name="percentage",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
