site_name: Wattle Cloud Platform
docs_dir: docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight

nav:
  - Home: index.md
  - Technical Guide:
      - Installation: technical-guide/installation.md
      - Model Setup: technical-guide/model-setup.md
      - Commands: technical-guide/commands.md
  - User Guide:
      - Order Certificate: user-guide/order-certificate.md
      - Order Fulfilment: user-guide/order-fulfilment.md
      - Download Certificate: user-guide/download-certificate.md
  - Troubleshooting:
      - Common Issues: troubleshooting/common-issues.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - toc:
      permalink: true
